# Every day at 7am UTC check if there have been any commits or if
# any of the dependencies have been updated

name: Nightly

on:
  schedule:
    - cron: '0 7 * * *'
  workflow_dispatch:

jobs:
  check-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Activity Check
      run: |
        curl -sL https://api.github.com/repos/$GITHUB_REPOSITORY/commits | jq -r '.[0]' > $HOME/commit.json
        date="$(jq -r '.commit.author.date' $HOME/commit.json)"
        timestamp=$(date --utc -d "$date" +%s)
        days=$(( ( $(date --utc +%s) - $timestamp ) / 86400 ))
        rm -f $HOME/commit.json
        if [ $days -lt 1 ]; then
          echo "CREATE_BUILD=true" >> $GITHUB_ENV
          # come back at some point and add the version number
          # curl -sL https://api.github.com/repos/$GITHUB_REPOSITORY/releases | jq -r '[.[] | select(.tag_name | contains(["dev", "b"]) | not)][0]' > $HOME/release.json
          # tag_name = "$(jq -r '.tag_name' $HOME/release.json)"
          # 0.8.1b0
          # 0.8.1     0.8.2a0.dev*
          # 0.8.1a0   0.8.2a1.dev*
          # rm -f $HOME/release.json
          clean_date=$(date --utc +%Y%m%d%H%M)
          echo "DATE=$clean_date" >> $GITHUB_ENV
          echo "TAG_NAME=0.0.0a0.dev$clean_date" >> $GITHUB_ENV
        fi
      shell: bash

    - name: Create Release
      if: ${{ env.CREATE_BUILD }} == 'true'
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.JGC_RELEASE_TOKEN }}
      with:
        tag_name: ${{ env.TAG_NAME }}
        release_name: Nightly ${{ env.DATE }}
        draft: false
        prerelease: true
